title: Henri Sandifer
description: >
  <p><strong>Data Engineer</strong> with a microbiology & agronomy background.<br>
  Skilled in Python, SQL and cloud pipelines.<br>
  <em>Building infrastructure that turns messy datastreams into actionable resources.</em></p>
  <p>ğŸŒ Languages: Fluent in English, French, Italian</p>
logo: 132948433.jpeg
theme: jekyll-theme-minimal
